### PR TITLE
feature: unarchive files (zip)

### PR DESCRIPTION
**Pull request by pabloarosado**
Migrate `extract_zip` to `io.local.decompress_file`. I renamed it that way because we may want to generalize it to other compressed formats in the future.
I added tests checking the functionality for local files, not remote files.

### CODE REVIEW

**Comment by pabloarosado** [comment]
Hi @Marigold, @lucasrodes and I were talking about this PR. It's not great that the new function `decompress_file`, in `io.local` imports the `web` module. But I don't see a clear solution. The only one I can think of is to have two separate functions, one `io.local.decompress_local_file` and another `web.decompress_remote_file`, for example. Do you have any other suggestion, or do you think it's no big deal to have some interdependencies of modules. Thanks.

**Comment by Marigold** [comment]
@pabloarosado I think it's totally fine. We can start thinking about this once we start running into cyclical imports, but since it's within one repo I wouldn't overthink it. (What's worse is that datautils depends on catalog and I'd need it to be the opposite)

**Comment by lucasrodes** [comment]
I'll try to draft a proposal soon for this. But my first thinking is:

- have local functions in `io.local`
- define a decorator using `download_file_from_url`
- use the local functions together with the decorator to enable remote capabilities. Place this functions in, e.g `io.__init__`

**Comment by lucasrodes** [comment]
Proposed an enhanced version of this in #45

**Review by lucasrodes — APPROVED** [review]

**Pull request merged**
